# Shark Attack

In [19]:
import pandas as pd

import xlrd

df = pd.read_excel("GSAF5.xls")

In [20]:
df

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,...,Great White Shark,US Sun: Mendocino Coast News:Melissa Michaelson:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,...,Unknown shark 5ft (1.5m),People Magazine: Kevin McMurray Trackingsharks...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,...,Great White Shark 10ft (3m),Perth Now: Kevin McMurray Trackingsharks.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,...,Unknown,News.com.au: ABC News: Andy Currie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata near Point Magnin,Wing Foiling,Cyril Chevalier,M,55,...,Tiger or bull shark implicated,Johannes Marchand: Andy Currie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN
7080,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN

In [21]:
#data cleaning column names step 1
df.columns=df.columns.str.strip()
print(df)

               Date    Year        Type             Country  \
0        18th March  2026.0  Unprovoked                 USA
1        14th March  2026.0  Unprovoked           Australia
2        10th March  2026.0  Unprovoked           Australia
3         5th March  2026.0  Unprovoked           Australia
4     22nd February  2026.0  Unprovoked       New Caledonia
...             ...     ...         ...                 ...
7077    Before 1903     0.0  Unprovoked           AUSTRALIA
7078    Before 1903     0.0  Unprovoked           AUSTRALIA
7079      1900-1905     0.0  Unprovoked                 USA
7080      1883-1889     0.0  Unprovoked              PANAMA
7081      1845-1853     0.0  Unprovoked  CEYLON (SRI LANKA)

                  State                             Location       Activity  \
0            California     Big River Beach Mendocino County        Surfing
1     Western Australia                              Exmouth       Swimming
2     Western Australia                              Exmouth  Wing Foiling
3            Queensland                  Lady Elliott Island     Snorkeling
4                Noumea          Anse Vata near Point Magnin  Wing Foiling
...                 ...                                  ...            ...
7077  Western Australia                          Roebuck Bay         Diving
7078  Western Australia                                  NaN   Pearl diving
7079     North Carolina                       Ocracoke Inlet       Swimming
7080                NaN                 Panama Bay 8ºN, 79ºW            NaN
7081   Eastern Province  Below the English fort, Trincomalee       Swimming

                       Name Sex   Age  ...                         Species  \
0                   Unknown   M    39  ...               Great White Shark
1                   Unknown   F     ?  ...        Unknown shark 5ft (1.5m)
2              Dave Daniell   M     ?  ...     Great White Shark 10ft (3m)
3                   Unknown  M   50's  ...                         Unknown
4           Cyril Chevalier   M    55  ...  Tiger or bull shark implicated
...                     ...  ..   ...  ...                             ...
7077                   male   M   NaN  ...                             NaN
7078                  Ahmun   M   NaN  ...                             NaN
7079  Coast Guard personnel   M   NaN  ...                             NaN
7080        Jules Patterson   M   NaN  ...                             NaN
7081                   male   M    15  ...                             NaN

                                                 Source  \
0      US Sun: Mendocino Coast News:Melissa Michaelson:
1     People Magazine: Kevin McMurray Trackingsharks...
2          Perth Now: Kevin McMurray Trackingsharks.com
3                    News.com.au: ABC News: Andy Currie
4                        Johannes Marchand: Andy Currie
...                                                 ...
7077                   H. Taunton; N. Bartlett,  p. 234
7078              H. Taunton; N. Bartlett,  pp. 233-234
7079               F. Schwartz, p.23; C. Creswell, GSAF
7080                                The Sun, 10/20/1938
7081                                         S.W. Baker

                                 pdf  \
0                                NaN
1                                NaN
2                                NaN
3                                NaN
4                                NaN
...                              ...
7077          ND-0005-RoebuckBay.pdf
7078               ND-0004-Ahmun.pdf
7079  ND-0003-Ocracoke_1900-1905.pdf
7080      ND-0002-JulesPatterson.pdf
7081              ND-0001-Ceylon.pdf

                                           href formula  \
0                                                   NaN
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
7077  http://sharkattackfile.net/spreadsheets/pdf_di...
7078  http://sharkattackfile.net/spreadsheets/pdf_di...
7079  http://sharkattackfile.net/spreadsheets/pdf_di...
7080  http://sharkattackfile.net/spreadsheets/pdf_di...
7081  http://sharkattackfile.net/spreadsheets/pdf_di...

                                                   href Case Number  \
0                                                   NaN         NaN
1                                                   NaN         NaN
2                                                   NaN         NaN
3                                                   NaN         NaN
4                                                   NaN         NaN
...                                                 ...         ...
7077  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0005
7078  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0004
7079  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0003
7080  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0002
7081  http://sharkattackfile.net/spreadsheets/pdf_di...     ND.0001

     Case Number.1 original order Unnamed: 21 Unnamed: 22
0              NaN            NaN         NaN         NaN
1              NaN            NaN         NaN         NaN
2              NaN            NaN         NaN         NaN
3              NaN            NaN         NaN         NaN
4              NaN            NaN         NaN         NaN
...            ...            ...         ...         ...
7077       ND.0005            6.0         NaN         NaN
7078       ND.0004            5.0         NaN         NaN
7079       ND.0003            4.0         NaN         NaN
7080       ND.0002            3.0         NaN         NaN
7081       ND.0001            2.0         NaN         NaN

[7082 rows x 23 columns]

In [22]:
#step 2 Handling null values

df.isnull().sum()

Date                 0
Year                 2
Type                18
Country             50
State              487
Location           567
Activity           583
Name               218
Sex                578
Age               2994
Injury              35
Fatal Y/N          561
Time              3527
Species           3131
Source              20
pdf                283
href formula       288
href               286
Case Number        284
Case Number.1      285
original order     283
Unnamed: 21       7081
Unnamed: 22       7080
dtype: int64

In [23]:
# Drop obvious irrelevent columns
df = df.drop(columns=[
    "Unnamed: 21", "Unnamed: 22",
    "href", "href formula", "pdf",
    "Case Number.1"
], errors="ignore")
df

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source,Case Number,original order
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,Injuries to both legs and feet,N,1715hrs,Great White Shark,US Sun: Mendocino Coast News:Melissa Michaelson:,NaN,NaN
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,Minor injuries,N,1015hrs,Unknown shark 5ft (1.5m),People Magazine: Kevin McMurray Trackingsharks...,NaN,NaN
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,None reported damage to board,N,0800hrs,Great White Shark 10ft (3m),Perth Now: Kevin McMurray Trackingsharks.com,NaN,NaN
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,Lacerations elbow and abdomen,N,0815hrs,Unknown,News.com.au: ABC News: Andy Currie,NaN,NaN
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata near Point Magnin,Wing Foiling,Cyril Chevalier,M,55,Deep wounds arms and legs,Y,?,Tiger or bull shark implicated,Johannes Marchand: Andy Currie,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND.0005,6.0
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND.0004,5.0
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND.0003,4.0
7080,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND.0002,3.0
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND.0001,2.0

In [24]:
#Remove columns where more than 50% of values are missing
df = df.dropna(axis=1, thresh=len(df) * 0.5)#keeps columns only with enough data
df

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source,Case Number,original order
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,Injuries to both legs and feet,N,1715hrs,Great White Shark,US Sun: Mendocino Coast News:Melissa Michaelson:,NaN,NaN
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,Minor injuries,N,1015hrs,Unknown shark 5ft (1.5m),People Magazine: Kevin McMurray Trackingsharks...,NaN,NaN
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,None reported damage to board,N,0800hrs,Great White Shark 10ft (3m),Perth Now: Kevin McMurray Trackingsharks.com,NaN,NaN
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,Lacerations elbow and abdomen,N,0815hrs,Unknown,News.com.au: ABC News: Andy Currie,NaN,NaN
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata near Point Magnin,Wing Foiling,Cyril Chevalier,M,55,Deep wounds arms and legs,Y,?,Tiger or bull shark implicated,Johannes Marchand: Andy Currie,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND.0005,6.0
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND.0004,5.0
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND.0003,4.0
7080,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND.0002,3.0
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND.0001,2.0

In [25]:
# Remove any remaining unnamed columns
df = df.loc[:, ~df.columns.str.contains("^Unnamed")]
df

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source,Case Number,original order
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,Injuries to both legs and feet,N,1715hrs,Great White Shark,US Sun: Mendocino Coast News:Melissa Michaelson:,NaN,NaN
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,Minor injuries,N,1015hrs,Unknown shark 5ft (1.5m),People Magazine: Kevin McMurray Trackingsharks...,NaN,NaN
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,None reported damage to board,N,0800hrs,Great White Shark 10ft (3m),Perth Now: Kevin McMurray Trackingsharks.com,NaN,NaN
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,Lacerations elbow and abdomen,N,0815hrs,Unknown,News.com.au: ABC News: Andy Currie,NaN,NaN
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata near Point Magnin,Wing Foiling,Cyril Chevalier,M,55,Deep wounds arms and legs,Y,?,Tiger or bull shark implicated,Johannes Marchand: Andy Currie,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND.0005,6.0
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND.0004,5.0
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND.0003,4.0
7080,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND.0002,3.0
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND.0001,2.0

In [26]:
#Remove duplicate rows
df = df.drop_duplicates()
df

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source,Case Number,original order
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,Injuries to both legs and feet,N,1715hrs,Great White Shark,US Sun: Mendocino Coast News:Melissa Michaelson:,NaN,NaN
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,Minor injuries,N,1015hrs,Unknown shark 5ft (1.5m),People Magazine: Kevin McMurray Trackingsharks...,NaN,NaN
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,None reported damage to board,N,0800hrs,Great White Shark 10ft (3m),Perth Now: Kevin McMurray Trackingsharks.com,NaN,NaN
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,Lacerations elbow and abdomen,N,0815hrs,Unknown,News.com.au: ABC News: Andy Currie,NaN,NaN
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata near Point Magnin,Wing Foiling,Cyril Chevalier,M,55,Deep wounds arms and legs,Y,?,Tiger or bull shark implicated,Johannes Marchand: Andy Currie,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND.0005,6.0
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND.0004,5.0
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND.0003,4.0
7080,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND.0002,3.0
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND.0001,2.0

In [27]:
#Handles missing values
df = df.fillna({
    "Country": "Unknown",
    "State": "Unknown",
    "Location": "Unknown",
    "Activity": "Unknown",
    "Sex": "Unknown",
    "Age": "Unknown",
    "Fatal Y/N": "Unknown",
    "Species": "Unknown"
})
df

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source,Case Number,original order
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,Injuries to both legs and feet,N,1715hrs,Great White Shark,US Sun: Mendocino Coast News:Melissa Michaelson:,NaN,NaN
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,Minor injuries,N,1015hrs,Unknown shark 5ft (1.5m),People Magazine: Kevin McMurray Trackingsharks...,NaN,NaN
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,None reported damage to board,N,0800hrs,Great White Shark 10ft (3m),Perth Now: Kevin McMurray Trackingsharks.com,NaN,NaN
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,Lacerations elbow and abdomen,N,0815hrs,Unknown,News.com.au: ABC News: Andy Currie,NaN,NaN
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata near Point Magnin,Wing Foiling,Cyril Chevalier,M,55,Deep wounds arms and legs,Y,?,Tiger or bull shark implicated,Johannes Marchand: Andy Currie,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,Unknown,FATAL,Y,NaN,Unknown,"H. Taunton; N. Bartlett, p. 234",ND.0005,6.0
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Unknown,Pearl diving,Ahmun,M,Unknown,FATAL,Y,NaN,Unknown,"H. Taunton; N. Bartlett, pp. 233-234",ND.0004,5.0
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,Unknown,FATAL,Y,NaN,Unknown,"F. Schwartz, p.23; C. Creswell, GSAF",ND.0003,4.0
7080,1883-1889,0.0,Unprovoked,PANAMA,Unknown,"Panama Bay 8ºN, 79ºW",Unknown,Jules Patterson,M,Unknown,FATAL,Y,NaN,Unknown,"The Sun, 10/20/1938",ND.0002,3.0
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,Unknown,S.W. Baker,ND.0001,2.0

In [28]:
#Handles missing values
df = df.fillna({
    "Country": "Unknown",
    "State": "Unknown",
    "Location": "Unknown",
    "Activity": "Unknown",
    "Sex": "Unknown",
    "Age": "Unknown",
    "Fatal Y/N": "Unknown",
    "Species": "Unknown"
})
df

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source,Case Number,original order
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,Injuries to both legs and feet,N,1715hrs,Great White Shark,US Sun: Mendocino Coast News:Melissa Michaelson:,NaN,NaN
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,Minor injuries,N,1015hrs,Unknown shark 5ft (1.5m),People Magazine: Kevin McMurray Trackingsharks...,NaN,NaN
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,None reported damage to board,N,0800hrs,Great White Shark 10ft (3m),Perth Now: Kevin McMurray Trackingsharks.com,NaN,NaN
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,Lacerations elbow and abdomen,N,0815hrs,Unknown,News.com.au: ABC News: Andy Currie,NaN,NaN
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata near Point Magnin,Wing Foiling,Cyril Chevalier,M,55,Deep wounds arms and legs,Y,?,Tiger or bull shark implicated,Johannes Marchand: Andy Currie,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,Unknown,FATAL,Y,NaN,Unknown,"H. Taunton; N. Bartlett, p. 234",ND.0005,6.0
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Unknown,Pearl diving,Ahmun,M,Unknown,FATAL,Y,NaN,Unknown,"H. Taunton; N. Bartlett, pp. 233-234",ND.0004,5.0
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,Unknown,FATAL,Y,NaN,Unknown,"F. Schwartz, p.23; C. Creswell, GSAF",ND.0003,4.0
7080,1883-1889,0.0,Unprovoked,PANAMA,Unknown,"Panama Bay 8ºN, 79ºW",Unknown,Jules Patterson,M,Unknown,FATAL,Y,NaN,Unknown,"The Sun, 10/20/1938",ND.0002,3.0
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,Unknown,S.W. Baker,ND.0001,2.0

In [29]:
#manipulating strings
df["Sex"] = df["Sex"].str.upper().str.strip()
df["Fatal Y/N"] = df["Fatal Y/N"].str.upper().str.strip()
df

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source,Case Number,original order
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,Injuries to both legs and feet,N,1715hrs,Great White Shark,US Sun: Mendocino Coast News:Melissa Michaelson:,NaN,NaN
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,Minor injuries,N,1015hrs,Unknown shark 5ft (1.5m),People Magazine: Kevin McMurray Trackingsharks...,NaN,NaN
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,None reported damage to board,N,0800hrs,Great White Shark 10ft (3m),Perth Now: Kevin McMurray Trackingsharks.com,NaN,NaN
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,Lacerations elbow and abdomen,N,0815hrs,Unknown,News.com.au: ABC News: Andy Currie,NaN,NaN
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata near Point Magnin,Wing Foiling,Cyril Chevalier,M,55,Deep wounds arms and legs,Y,?,Tiger or bull shark implicated,Johannes Marchand: Andy Currie,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,Unknown,FATAL,Y,NaN,Unknown,"H. Taunton; N. Bartlett, p. 234",ND.0005,6.0
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Unknown,Pearl diving,Ahmun,M,Unknown,FATAL,Y,NaN,Unknown,"H. Taunton; N. Bartlett, pp. 233-234",ND.0004,5.0
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,Unknown,FATAL,Y,NaN,Unknown,"F. Schwartz, p.23; C. Creswell, GSAF",ND.0003,4.0
7080,1883-1889,0.0,Unprovoked,PANAMA,Unknown,"Panama Bay 8ºN, 79ºW",Unknown,Jules Patterson,M,Unknown,FATAL,Y,NaN,Unknown,"The Sun, 10/20/1938",ND.0002,3.0
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,Unknown,S.W. Baker,ND.0001,2.0

In [30]:
#Regex to extract numerical ages
import re
df["Age_clean"] = (
    df["Age"]
    .astype(str)
    .apply(lambda x: re.findall(r"\d+", x))
    .apply(lambda x: int(x[0]) if x else None)
)
df

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source,Case Number,original order,Age_clean
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,Injuries to both legs and feet,N,1715hrs,Great White Shark,US Sun: Mendocino Coast News:Melissa Michaelson:,NaN,NaN,39.0
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,Minor injuries,N,1015hrs,Unknown shark 5ft (1.5m),People Magazine: Kevin McMurray Trackingsharks...,NaN,NaN,NaN
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,None reported damage to board,N,0800hrs,Great White Shark 10ft (3m),Perth Now: Kevin McMurray Trackingsharks.com,NaN,NaN,NaN
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,Lacerations elbow and abdomen,N,0815hrs,Unknown,News.com.au: ABC News: Andy Currie,NaN,NaN,50.0
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata near Point Magnin,Wing Foiling,Cyril Chevalier,M,55,Deep wounds arms and legs,Y,?,Tiger or bull shark implicated,Johannes Marchand: Andy Currie,NaN,NaN,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,Unknown,FATAL,Y,NaN,Unknown,"H. Taunton; N. Bartlett, p. 234",ND.0005,6.0,NaN
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Unknown,Pearl diving,Ahmun,M,Unknown,FATAL,Y,NaN,Unknown,"H. Taunton; N. Bartlett, pp. 233-234",ND.0004,5.0,NaN
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,Unknown,FATAL,Y,NaN,Unknown,"F. Schwartz, p.23; C. Creswell, GSAF",ND.0003,4.0,NaN
7080,1883-1889,0.0,Unprovoked,PANAMA,Unknown,"Panama Bay 8ºN, 79ºW",Unknown,Jules Patterson,M,Unknown,FATAL,Y,NaN,Unknown,"The Sun, 10/20/1938",ND.0002,3.0,NaN
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,Unknown,S.W. Baker,ND.0001,2.0,15.0

In [31]:
#Extract Age 
df["Age_clean"] = df["Age"].str.extract(r"(\d+)")

In [32]:
#Data cleaning in Date format
df["Date_clean"] = df["Date"].str.replace(
    r"(\d+)(st|nd|rd|th)", r"\1", regex=True
)
df

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source,Case Number,original order,Age_clean,Date_clean
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,Injuries to both legs and feet,N,1715hrs,Great White Shark,US Sun: Mendocino Coast News:Melissa Michaelson:,NaN,NaN,39,18 March
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,Minor injuries,N,1015hrs,Unknown shark 5ft (1.5m),People Magazine: Kevin McMurray Trackingsharks...,NaN,NaN,NaN,14 March
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,None reported damage to board,N,0800hrs,Great White Shark 10ft (3m),Perth Now: Kevin McMurray Trackingsharks.com,NaN,NaN,NaN,10 March
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,Lacerations elbow and abdomen,N,0815hrs,Unknown,News.com.au: ABC News: Andy Currie,NaN,NaN,50,5 March
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata near Point Magnin,Wing Foiling,Cyril Chevalier,M,55,Deep wounds arms and legs,Y,?,Tiger or bull shark implicated,Johannes Marchand: Andy Currie,NaN,NaN,55,22 February
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,Unknown,FATAL,Y,NaN,Unknown,"H. Taunton; N. Bartlett, p. 234",ND.0005,6.0,NaN,Before 1903
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Unknown,Pearl diving,Ahmun,M,Unknown,FATAL,Y,NaN,Unknown,"H. Taunton; N. Bartlett, pp. 233-234",ND.0004,5.0,NaN,Before 1903
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,Unknown,FATAL,Y,NaN,Unknown,"F. Schwartz, p.23; C. Creswell, GSAF",ND.0003,4.0,NaN,1900-1905
7080,1883-1889,0.0,Unprovoked,PANAMA,Unknown,"Panama Bay 8ºN, 79ºW",Unknown,Jules Patterson,M,Unknown,FATAL,Y,NaN,Unknown,"The Sun, 10/20/1938",ND.0002,3.0,NaN,1883-1889
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,Unknown,S.W. Baker,ND.0001,2.0,15,1845-1853

In [33]:
#standartize Activity
df["Activity_group"] = df["Activity"].str.lower().apply(
    lambda x: "Swimming" if "swim" in x else
              "Surfing" if "surf" in x else
              "Fishing" if "fish" in x else
              "Diving" if "dive" in x else
              "Other"
)
df

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source,Case Number,original order,Age_clean,Date_clean,Activity_group
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,Injuries to both legs and feet,N,1715hrs,Great White Shark,US Sun: Mendocino Coast News:Melissa Michaelson:,NaN,NaN,39,18 March,Surfing
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,Minor injuries,N,1015hrs,Unknown shark 5ft (1.5m),People Magazine: Kevin McMurray Trackingsharks...,NaN,NaN,NaN,14 March,Swimming
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,None reported damage to board,N,0800hrs,Great White Shark 10ft (3m),Perth Now: Kevin McMurray Trackingsharks.com,NaN,NaN,NaN,10 March,Other
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,Lacerations elbow and abdomen,N,0815hrs,Unknown,News.com.au: ABC News: Andy Currie,NaN,NaN,50,5 March,Other
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata near Point Magnin,Wing Foiling,Cyril Chevalier,M,55,Deep wounds arms and legs,Y,?,Tiger or bull shark implicated,Johannes Marchand: Andy Currie,NaN,NaN,55,22 February,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,Unknown,FATAL,Y,NaN,Unknown,"H. Taunton; N. Bartlett, p. 234",ND.0005,6.0,NaN,Before 1903,Other
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Unknown,Pearl diving,Ahmun,M,Unknown,FATAL,Y,NaN,Unknown,"H. Taunton; N. Bartlett, pp. 233-234",ND.0004,5.0,NaN,Before 1903,Other
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,Unknown,FATAL,Y,NaN,Unknown,"F. Schwartz, p.23; C. Creswell, GSAF",ND.0003,4.0,NaN,1900-1905,Swimming
7080,1883-1889,0.0,Unprovoked,PANAMA,Unknown,"Panama Bay 8ºN, 79ºW",Unknown,Jules Patterson,M,Unknown,FATAL,Y,NaN,Unknown,"The Sun, 10/20/1938",ND.0002,3.0,NaN,1883-1889,Other
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,Unknown,S.W. Baker,ND.0001,2.0,15,1845-1853,Swimming

In [34]:
#standardize location
import re
df["Location"] = df["Location"].str.replace(r"Off|Near", "", regex=True, flags=re.IGNORECASE).str.strip()
df

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source,Case Number,original order,Age_clean,Date_clean,Activity_group
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,Injuries to both legs and feet,N,1715hrs,Great White Shark,US Sun: Mendocino Coast News:Melissa Michaelson:,NaN,NaN,39,18 March,Surfing
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,Minor injuries,N,1015hrs,Unknown shark 5ft (1.5m),People Magazine: Kevin McMurray Trackingsharks...,NaN,NaN,NaN,14 March,Swimming
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,None reported damage to board,N,0800hrs,Great White Shark 10ft (3m),Perth Now: Kevin McMurray Trackingsharks.com,NaN,NaN,NaN,10 March,Other
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,Lacerations elbow and abdomen,N,0815hrs,Unknown,News.com.au: ABC News: Andy Currie,NaN,NaN,50,5 March,Other
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata Point Magnin,Wing Foiling,Cyril Chevalier,M,55,Deep wounds arms and legs,Y,?,Tiger or bull shark implicated,Johannes Marchand: Andy Currie,NaN,NaN,55,22 February,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,Unknown,FATAL,Y,NaN,Unknown,"H. Taunton; N. Bartlett, p. 234",ND.0005,6.0,NaN,Before 1903,Other
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Unknown,Pearl diving,Ahmun,M,Unknown,FATAL,Y,NaN,Unknown,"H. Taunton; N. Bartlett, pp. 233-234",ND.0004,5.0,NaN,Before 1903,Other
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,Unknown,FATAL,Y,NaN,Unknown,"F. Schwartz, p.23; C. Creswell, GSAF",ND.0003,4.0,NaN,1900-1905,Swimming
7080,1883-1889,0.0,Unprovoked,PANAMA,Unknown,"Panama Bay 8ºN, 79ºW",Unknown,Jules Patterson,M,Unknown,FATAL,Y,NaN,Unknown,"The Sun, 10/20/1938",ND.0002,3.0,NaN,1883-1889,Other
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,Unknown,S.W. Baker,ND.0001,2.0,15,1845-1853,Swimming

In [35]:
print(df["Location"].head(10))

0         Big River Beach Mendocino County
1                                  Exmouth
2                                  Exmouth
3                      Lady Elliott Island
4                  Anse Vata  Point Magnin
5                            Caribbean Sea
6               Del Chifre Beach in Olinda
7                Angels Beach East Ballina
8               Cooee Beach west of Burnie
9    Point Plomber North of Port Macquarie
Name: Location, dtype: object

In [43]:
# Remove 'st', 'nd', 'rd', 'th'
df["Date"] = df["Date"].astype(str).str.replace(r'(\d+)(st|nd|rd|th)', r'\1', regex=True)

# Combine with Year column
df["Date_str"] = df["Date"] + " " + df["Year"].astype("Int64").astype(str)
df

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Time,Species,Source,Case Number,original order,Age_clean,Date_clean,Activity_group,Date_str,Date_parsed
0,18 March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,...,1715hrs,Great White Shark,US Sun: Mendocino Coast News:Melissa Michaelson:,NaN,NaN,39,18 March,Surfing,18 March 2026,2026-03-18
1,14 March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,...,1015hrs,Unknown shark 5ft (1.5m),People Magazine: Kevin McMurray Trackingsharks...,NaN,NaN,NaN,14 March,Swimming,14 March 2026,2026-03-14
2,10 March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,...,0800hrs,Great White Shark 10ft (3m),Perth Now: Kevin McMurray Trackingsharks.com,NaN,NaN,NaN,10 March,Other,10 March 2026,2026-03-10
3,5 March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,...,0815hrs,Unknown,News.com.au: ABC News: Andy Currie,NaN,NaN,50,5 March,Other,5 March 2026,2026-03-05
4,22 February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata Point Magnin,Wing Foiling,Cyril Chevalier,M,55,...,?,Tiger or bull shark implicated,Johannes Marchand: Andy Currie,NaN,NaN,55,22 February,Other,22 February 2026,2026-02-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,Unknown,...,NaN,Unknown,"H. Taunton; N. Bartlett, p. 234",ND.0005,6.0,NaN,Before 1903,Other,Before 1903 0,NaT
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Unknown,Pearl diving,Ahmun,M,Unknown,...,NaN,Unknown,"H. Taunton; N. Bartlett, pp. 233-234",ND.0004,5.0,NaN,Before 1903,Other,Before 1903 0,NaT
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,Unknown,...,NaN,Unknown,"F. Schwartz, p.23; C. Creswell, GSAF",ND.0003,4.0,NaN,1900-1905,Swimming,1900-1905 0,NaT
7080,1883-1889,0.0,Unprovoked,PANAMA,Unknown,"Panama Bay 8ºN, 79ºW",Unknown,Jules Patterson,M,Unknown,...,NaN,Unknown,"The Sun, 10/20/1938",ND.0002,3.0,NaN,1883-1889,Other,1883-1889 0,NaT
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,...,NaN,Unknown,S.W. Baker,ND.0001,2.0,15,1845-1853,Swimming,1845-1853 0,NaT